### PR TITLE
Login signup

### PR DESCRIPTION
**Pull request by BidisaChowdhury**
Added the backend for login and signup page using PHP...

### CODE REVIEW

**Comment by satatya** [comment]
This was a very big issue to resolve, so can you once come to google meet today or tomorrow to display your work to both of us(me and @abhigyan-c ), then we could verify this stuff and then close this issue after merging your PR. You can attach your emai-id so that we can communicate further regarding this issue and the e-meeting. Thank You.

**Comment by satatya** [comment]
@BidisaChowdhury do reply by tomorrow night 12.

**Comment by BidisaChowdhury** [comment]
Yupp...Can we start the meeting from 8:30 p.m tomorrow?

My Email :  chowdhury.bidisa02@gmail.com

**Comment by satatya** [comment]
yes

**Pull request merged**
