### PR TITLE
modified the UI

### PR DESCRIPTION
**Pull request by Hitanshi-Singh**
-added text shadow to make the text on the video visible
-modified the ui of login form 
-scroll bar colour changed

### CODE REVIEW

**Comment by satatya** [comment]
hi @Hitanshi-Singh , pls attach a screenshot of your work for our project lead @abhigyan-c to check before merging your pull request. Thank you ...

**Comment by Hitanshi-Singh** [comment]
> hi @Hitanshi-Singh , pls attach a screenshot of your work for our project lead @abhigyan-c to check before merging your pull request. Thank you ...

Screenshot_20230206_152309
Screenshot_20230206_152548
Screenshot_20230206_152557
Screenshot_20230206_152238

**Comment by Hitanshi-Singh** [comment]
Sir, I have attached all the relevant screenshots

**Comment by Hitanshi-Singh** [comment]
sir for the navigation links issue..this pull request was causing a conflict..i will resolve it in another pull request

**Comment by satatya** [comment]
great work... you may progress further on some issues/documentations that you'd like to work on. We will merge this PR by tomorrow 12, after @abhigyan-c reviews the changes.

**Comment by satatya** [comment]
@abhigyan-c has asked u to resolve the conflicts before he can merge this PR

**Comment by Hitanshi-Singh** [comment]
> @abhigyan-c has asked u to resolve the conflicts before he can merge this PR

i did..but the new pull request was merged that was opened just two hours ago caused it. my pull req is 2 days old. is there something wrong with it that you are not merging it?

**Pull request closed without merging**
