### PR TITLE
Formatted html files

### PR DESCRIPTION
**Pull request by aviiciii**
### Proper HTML Formatting of files 

**Files Formatted:**

1. about.html
2. andaman.html
3. ap.html
4. card.html
5. chitrakote.html
6. contactus.html

@satatya @abhigyan-c Kindly review these formatting process and accept the pull request.
Once this request has been accepted, I will work on more HTML files.

### CODE REVIEW

**Comment by aviiciii** [comment]
Kindly add label diversion2k23 to this pull request.

**Comment by satatya** [comment]
pls attach screenshots for me and @abhigyan-c to view your work before we can merge ur PR.

**Comment by aviiciii** [comment]
### HTML Formatting Previews

@satatya and @abhigyan-c 
Kindly view the given below snippets of code for the indentation and formatting used in the html files. Below snippets are from about.html. 


### 1.
**Before**

image

 **After**

image

### 2.
**Before**

image

**After**

image

### 3.
**Before**
image


**After**
image



For more detailed code, check the html files mentioned in the above comment.

**Comment by satatya** [comment]
#diversion2k23

**Pull request merged**
