### PR TITLE
Formatted all Javascript files

### PR DESCRIPTION
**Pull request by aviiciii**
## Formatted Javascript files

This pull request is under issue #17 . 

All Javascript files present in the repo are formattted properly with indentation using tabs.

### Code snippets:
**1.**
```
function myFunction(event) {
	event.preventDefault();
	alert("Success!!Your details have been successfully submitted!Your concerns will soon be addressed!");
}
console.log("Successfully connected");
function validateForm() {
	let x = document.forms["myForm"]["fname"].value;
	let y = document.forms["myForm"]["email"].value;
	if (x == "") {
		alert("Name must be filled out");
		return false;
	}
	if (y == "") {
		alert("Email must be filled out");
	}
}

function notEmpty(elem, helperMsg) {
	if (elem.value.length == 0) {
		alert(helperMsg);
		elem.focus();
		return false;
	}
	return true;
}
```

**2.**
```
function _classCallCheck(instance, Constructor) {
		if (!(instance instanceof Constructor)) {
			throw new TypeError("Cannot call a class as a function");
		}
	}

	var _createClass = (function () {
		function defineProperties(target, props) {
			for (var i = 0; i < props.length; i++) {
				var descriptor = props[i];
				descriptor.enumerable = descriptor.enumerable || false;
				descriptor.configurable = true;
				if ("value" in descriptor) descriptor.writable = true;
				Object.defineProperty(target, descriptor.key, descriptor);
			}
		}

		return function (Constructor, protoProps, staticProps) {
			if (protoProps) defineProperties(Constructor.prototype, protoProps);
			if (staticProps) defineProperties(Constructor, staticProps);
			return Constructor;
		};
	})();

	function isIn(needle, haystack) {
		return haystack.indexOf(needle) >= 0;
	}

	function extend(custom, defaults) {
		for (var key in defaults) {
			if (custom[key] == null) {
				var value = defaults[key];
				custom[key] = value;
			}
		}
		return custom;
	}
```

### CODE REVIEW

**Comment by aviiciii** [comment]
@satatya and @abhigyan-c Kindly review my pull request.

**Comment by satatya** [comment]
You sure 'bout this right? Coz the guy who was responsible for the javascript codes/.js files last time round, is not participating this year, so solving javascript errors would be a little tough and time-consuming. @aviiciii

**Comment by aviiciii** [comment]
@satatya Yes, I can only formatted the code and haven't changed any part of the Javascript. Anyways, you have option to revert if there happens to be issues.

**Comment by satatya** [comment]
yea sure thanx

**Pull request merged**
