### PR TITLE
Updated UI of Rajasthan section

### PR DESCRIPTION
**Pull request by Tapo41**
I added a shadow by creating a container(also by adjusting the margin) which will give a classy  look to the website .I changed this for all (HISTORY,ITINARARY,HOTELS ,HOW TO REACH) the sections of Rajasthan page.

### CODE REVIEW

**Comment by Tapo41** [comment]
Screenshot_20230211_155419

Before
Screenshot_20230211_160551
After

**Comment by satatya** [comment]
great... can you add this effect to the other "places of interest" as well?

**Comment by Tapo41** [comment]
@satatya  Yes I will

**Comment by satatya** [comment]
@Tapo41 can you tell me your full name? We need to add it in the contributors section.

**Comment by Tapo41** [comment]
@satatya My full name isTapojita Kar

**Pull request merged**
