### PR TITLE
update index.html

### PR DESCRIPTION
**Pull request by Tapo41**
updated background color and font color of room service

### CODE REVIEW

**Comment by Tapo41** [comment]
@abhigyan-c I contributed to this under diversion 2k23

**Comment by abhigyan-c** [comment]
Please send a screenshot of the changes.

**Comment by Tapo41** [comment]
https://live.staticflickr.com/65535/52666218437_77d9949c45_h.jpg

This is the link of screenshot @abhigyan-c 
I updated padding and the text alignment as well

**Comment by satatya** [comment]
great!

**Pull request merged**
